### ISSUE TITLE
WMS layer not working

### ISSUE THREAD

**Issue by Gazer75** [geofabrik/osmi_simple_views#42] opened 2022-04-25 01:00 UTC
Didn't know where to put this so figured I'd add it here.

None of the OSM Inspector wms layers listed in JOSM works any more.

The whole thing is described on the wiki at https://wiki.openstreetmap.org/wiki/OSM_Inspector/WxS

Opening one of the endpoints in a browser would normally return xml code for the layers, but instead its prompting a download of something.

**Comment by woodpeck** [comment] 2022-04-25 11:40
There was a bug in the GetCapabilities response in that it did not have a host name specified in the URLs and not all clients will use the same server from which they got the GetCapabilities response in these cases. This bug has been fixed now. However, this bug should not trigger "the download of something". The example link from the WxS page, http://tools.geofabrik.de/osmi/view/addresses/wxs?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetCapabilities, returns a proper XML document.

**Closed by woodpeck** 2022-04-25 11:40 UTC

**Comment by Gazer75** [comment] 2022-04-25 12:37
Tested on both Firefox and Chrome, and both download a file called wxs. That file is an xml document with the expected text I'd get from other such requests.

**Comment by woodpeck** [comment] 2022-04-25 22:44
Yes. That is the expected behaviour.

**Comment by Gazer75** [comment] 2022-04-26 03:11
Oh? Strange, other wms layers I've opened like that will simply display the xml code in the browser directly.

**Comment by woodpeck** [comment] 2022-04-26 08:53
That's because the `Content-type` is `application/vnd.ogc.wms_xml` and not `text/xml` and the browser doesn't recognize that. It is however the standard content type for a GetCapabilities response.
